[package]
name = "rust-vc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
dasp_ring_buffer = "0.11.0"
dasp_sample = "0.11.0"
log = "0.4.20"
simple_logger = "4.3.3"
